routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if(\Auth::check())
    return redirect('/contacts');
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('user/{user}','UserController@show');
Route::post('user/{user}/avatar','UserController@update_avatar');

Route::resource('reports', 'ReportController');
Route::resource('contacts', 'ContactController');


// Route::get('/{vue_capture?}', function () {
//     return view('index');
// })->where('vue_capture', '[\/\w\.-]*');

app/Contact.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Contact extends Model
{
    use SoftDeletes;

    protected $fillable = ['name','lastname','email','user_id','numbers'];

    protected $casts = [
        'numbers' => 'array',
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'avatar','name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use App\Contact;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class ContactController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        // $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        $name = $request->input('name');

        $query = Contact::select();

        if ($name){
            $query = $query->where('name','like', '%'.$name.'%')->orWhere('lastname','like', '%'.$name.'%');
        }

        $contacts = $query->where('user_id',Auth::user()->id)->get();

        return view('contacts.index', compact('contacts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('contacts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'name' => 'required|string|min:2|max:50',
            'lastname' => 'nullable|string|min:5|max:50',
            'email' => 'nullable|email',
            'numbers' => 'nullable|array',
        ]);

        $validatedData['user_id'] = Auth::user()->id;
        $validatedData['numbers'] = array_filter($validatedData['numbers']);

        Contact::create($validatedData);

        return redirect('/contacts')->with('success', 'Contato salvo!');
    }

     /**
     * Display the specified resource.
     *
     * @param  \App\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function show(Contact $contact)
    {
        return $contact;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function edit(Contact $contact)
    {
        $contact = $contact;
        return view('contacts.edit', compact('contact'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Contact $contact)
    {
        $validatedData = $request->validate([
            'name' => 'required|string|min:5|max:50',
            'lastname' => 'nullable|string|min:5|max:50',
            'email' => 'nullable|email',
            'numbers' => 'nullable|array',
            'numbers.*' => 'nullable|min:8|max:20',
        ]);

        if(isset($validatedData['numbers']))
        $validatedData['numbers'] = array_filter($validatedData['numbers']);

        $contact->fill($validatedData);
        $contact->save();

        return redirect('/contacts')->with('success', 'Contato atualizado!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function destroy(Contact $contact)
    {
        $contact->delete();

        return redirect('/contacts')->with('success', 'Contato removido com sucesso!');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ReportController.php
<?php

namespace App\Http\Controllers;

use App\Contact;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ReportController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $contacts_ct = Contact::where('user_id',Auth::user()->id)->where('numbers','like','%,%')->orWhere('numbers','like','[%"%]')->get();
        $contacts_st = Contact::where('user_id',Auth::user()->id)->where('numbers',NULL)->orWhere('numbers','like','[]')->get();

        return view('reports.index', compact('contacts_ct','contacts_st'));
    }


}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class UserController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $contact
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return Storage::get($user->avatar);
        // return $user->avatar;
        // return Storage::download($user->avatar);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $User
     * @return \Illuminate\Http\Response
     */
    public function update_avatar(Request $request, User $user)
    {
        $validatedData = $request->validate([
            'file' => 'required|image'
        ]);

        if($user->avatar != 'public/avatars/default.jpg')
        Storage::delete($user->avatar);

        $path = Storage::put('public/avatars', $validatedData['file']);

        $user->avatar = $path;
        $user->save();

        return str_replace("public/", "", $path);
    }

}

resources/views/contacts/create.blade.php
@extends('home')

@section('main')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">Adicionar Contato</h1>
        <div>
            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div><br />
            @endif
            <form method="post" action="{{ route('contacts.store') }}">
                @csrf
                <div class="form-group">
                    <label for="first_name">Nome:</label>
                    <input type="text" class="form-control" name="name" />
                </div>

                <div class="form-group">
                    <label for="last_name">Sobrenome:</label>
                    <input type="text" class="form-control" name="lastname" />
                </div>

                <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="text" class="form-control" name="email" />
                </div>

                <table class="table table-bordered table-hover" id="tab_logic">
                    <tbody>
                        <tr id='addr0'>
                            <td style="display: none;">1</td>
                            <td>
                                <input type="number" name='numbers[]' placeholder='Telefone' class="form-control" />
                            </td>
                        </tr>
                        <tr id='addr1'></tr>
                    </tbody>
                </table>

                <div class="form-group">
                    <a id="add_row" class="btn btn-danger pull-left">+</a> <a id="delete_row" class="btn btn-primary pull-left">-</a>
                </div>

                <button type="submit" class="btn btn-primary">Adicionar</button>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/contacts/edit.blade.php
<div class="row">
    <div class="col-sm-12">
        <h2 class="display-9">Atualize um contato</h1>

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br />
        @endif
        <form method="post" action="{{ route('contacts.update', $contact->id) }}">
            @method('PATCH')
            @csrf
            <div class="form-group">

                <label for="first_name">Primeiro nome:</label>
                <input type="text" class="form-control" name="name" value="{{ $contact->name }}" />
            </div>

            <div class="form-group">
                <label for="last_name">Sobrenome:</label>
                <input type="text" class="form-control" name="last_name" value="{{ $contact->lastname }}" />
            </div>

            <div class="form-group">
                <label for="email">Email:</label>
                <input type="text" class="form-control" name="email" value="{{ $contact->email }}" />
            </div>

            <table class="table table-bordered table-hover" id="tab_logic_edit">
                <tbody>

                    @foreach ($contact->numbers as $key => $number)
                    <tr id='addr_edit0'>
                        <td style="display:none;">{{$key}}</td>
                        <td>
                            <input type="number" name='numbers[]' placeholder='Telefone' value="{{$number}}" class="form-control" />
                        </td>
                    </tr>
                    @endforeach
                    <tr id='addr_edit1'></tr>
                </tbody>
            </table>

            <div class="form-group">
                <a id="add_row_edit" class="btn btn-danger pull-left">+</a>
            </div>


            <button type="submit" class="btn btn-primary">Atualizar</button>
            <br />
            <br />
            *Caso não queira adicionar mais telefones, deixe em branco.
        </form>
    </div>
</div>

<script type="text/javascript">
$(document).ready(function(){
    var i=1;
    $("#add_row_edit").click(function(){b=i-1
        // alert('teste');
        var semvalue = '<td style="display: none;">'+i+'</td> <td><input type="number" name="numbers[]" placeholder="Telefone" value="" class="form-control"></td>';
        $('#addr_edit'+i).html(semvalue).find('td:first-child').html(i+1);
        $('#tab_logic_edit').append('<tr id="addr_edit'+(i+1)+'"></tr>');
        i++;
    });

});
</script>

resources/views/contacts/index.blade.php
@extends('home')

@section('main')
<!-- Modal Dialog Delete -->
<div class="modal fade" id="confirmDelete" role="dialog" aria-labelledby="confirmDeleteLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Atenção!</h4>
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      </div>
      <div class="modal-body">
        <p>Você tem certeza que desejar remover esse contato?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
        <button type="button" class="btn btn-danger" id="confirm">Remover</button>
      </div>
    </div>
  </div>
</div>

<!-- Modal create new contact -->
<div class="modal fade" id="createContact" role="dialog" aria-labelledby="createContactLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Adicionar Contato</h4>
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      </div>
      <div class="modal-body">
        <form method="post" action="{{ route('contacts.store') }}">
          @csrf
          <div class="form-group">
            <label for="first_name">Nome:</label>
            <input type="text" class="form-control" name="name" />
          </div>

          <div class="form-group">
            <label for="last_name">Sobrenome:</label>
            <input type="text" class="form-control" name="lastname" />
          </div>

          <div class="form-group">
            <label for="email">Email:</label>
            <input type="text" class="form-control" name="email" />
          </div>

          <table class="table table-bordered table-hover" id="tab_logic">
            <tbody>
              <tr id='addr0'>
                <td style="display: none;">1</td>
                <td>
                  <input type="number" name='numbers[]' placeholder='Telefone' class="form-control" />
                </td>
              </tr>
              <tr id='addr1'></tr>
            </tbody>
          </table>

          <div class="form-group">
            <a id="add_row" class="btn btn-danger pull-left">+</a> <a id="delete_row" class="btn btn-primary pull-left">-</a>
          </div>

          <button type="submit" class="btn btn-primary">Adicionar</button>
        </form>
      </div>
      <!-- <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
        <button type="button" class="btn btn-danger" id="confirm">Remover</button>
      </div> -->
    </div>
  </div>
</div>


<div class="modal fade" id="dynamic-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body"></div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-12">
    @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}
    </div>
    @endif
  </div>
  <div>
    <button style="margin: 19px;" class="btn btn-primary" type="button" data-toggle="modal" data-target="#createContact">Novo contato</button>
  </div>
  <div>
    <a style="margin: 19px;" href="{{ route('reports.index')}}" class="btn btn-primary">Relatórios</a>
  </div>
  <div class="col-sm-12">
    <h1 class="display-3">Contatos</h1>
    <form action="contacts" method="get">
      <!-- Grid row -->
      <div class="form-row">
        <!-- Grid column -->
        <div class="col-lg-11">
          <!-- Material input -->
          <div class="md-form form-group">
            @if(isset($_GET['name']))
            <input type="text" class="form-control" name="name" placeholder="Pesquisar" value="{{$_GET['name']}}">
            @else
            <input type="text" class="form-control" name="name" placeholder="Pesquisar" value="">
            @endif
          </div>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-lg-1">
          <!-- Material input -->
          <div class="md-form form-group">
            <button type="submit" class="btn form-control btn-danger" type="button">
              🔎
            </button>
          </div>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->


    </form>
    <table class="table table-striped">
      <thead>
        <tr>

          <td>Name</td>
          <td>Email</td>
          <td>Telefone(s)</td>
          <td colspan=2>Ações</td>
        </tr>
      </thead>
      <tbody>
        @foreach($contacts as $contact)
        <tr>

          <td>{{$contact->name}} {{$contact->lastname}}</td>
          <td>{{$contact->email}}</td>
          <td>{{ implode(' - ', $contact->numbers) }}</td>
          <td>
            <button data-path="{{ route('contacts.edit',$contact->id) }}" class="btn btn-primary load-ajax-modal" role="button" data-toggle="modal" data-target="#dynamic-modal">
              <span class="glyphicon glyphicon-eye-open"></span> Editar
            </button>
          </td>
          <td>
            <form action="{{ route('contacts.destroy', $contact->id)}}" method="post">
              @csrf
              @method('DELETE')
              <button class="btn btn-xs btn-danger" type="button" data-toggle="modal" data-target="#confirmDelete" data-title="Atenção!" data-message="Você tem certeza em remover esse contato?">
                <i class="glyphicon glyphicon-trash"></i> Delete
              </button>
            </form>
          </td>
        </tr>
        @endforeach
      </tbody>
    </table>
    <div>
    </div>

    @endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  @yield('main')
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <!-- <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif -->
                        @else
                        <img src="/user/{{Auth::user()->id}}" id="preview_image" width="50" height="50">
                            <li class="nav-item dropdown">

                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <a class="dropdown-item" href="javascript:changeProfile();">
                                        {{ __('Alterar avatar') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
    <input type="file" id="file" style="display: none"/>
    <input type="hidden" id="file_name"/>
</body>
</html>


@if(Illuminate\Support\Facades\Auth::check())
<script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
<script type="text/javascript">
    function changeProfile() {
        $('#file').click();
    }

    $('#file').change(function () {
        if ($(this).val() != '') {
            upload(this);
        }
    });

    function upload(img) {
        var form_data = new FormData();
        form_data.append('file', img.files[0]);
        form_data.append('_token', '{{csrf_token()}}');
        $('#loading').css('display', 'block');
        $.ajax({
            url: "/user/{{Auth::user()->id}}/avatar",
            data: form_data,
            type: 'POST',
            contentType: false,
            processData: false,
            success: function (data) {
                if (data.fail) {
                    alert('teste');
                    $('#preview_image').attr('src', "user/{{Auth::user()->id}}");
                    alert(data.errors['file']);
                }
                else {
                    $('#file_name').val(data);
                    $('#preview_image').attr('src', "storage/"+data);
                }
                $('#loading').css('display', 'none');
            },
            error: function (xhr, status, error) {
                // alert('Ok3');
                $('#preview_image').attr('src', "{{asset('avatar')}}/" + data);
                alert(xhr.responseText);
                $('#preview_image').attr('src', "{{asset('images/noimage.jpg')}}");
            }
        });
    }
</script>
@endif

resources/views/reports/index.blade.php
@extends('home')

@section('main')

<div class="row">
<h1 class="display-4">Relatório</h2>
  <div class="col-sm-12">
    <br/>
    <h2 class="display-8">Contatos com telefone</h2>
    <table class="table table-striped">
      <thead>
        <tr>

          <td>Name</td>
          <td>Email</td>
          <td>Telefone(s)</td>
        </tr>
      </thead>
      <tbody>
        @foreach($contacts_ct as $contact)
        <tr>

          <td>{{$contact->name}} {{$contact->lastname}}</td>
          <td>{{$contact->email}}</td>
          <td>{{ implode(' - ', $contact->numbers) }}</td>
        </tr>
        @endforeach
      </tbody>
    </table>

  </div>
</div>


<div class="row">

  <div class="col-sm-12">
  <h2 class="display-8">Contatos sem telefone</h2>
    <table class="table table-striped">
      <thead>
        <tr>

          <td>Name</td>
          <td>Email</td>
          <td>Telefone(s)</td>
        </tr>
      </thead>
      <tbody>
        @foreach($contacts_st as $contact_st)
        <tr>

          <td>{{$contact_st->name}} {{$contact_st->lastname}}</td>
          <td>--</td>
          <td>-</td>
        </tr>
        @endforeach
      </tbody>
    </table>

  </div>
</div>



@endsection